apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-server
  namespace: default
  labels:
    app: mongo-server
    release: 1.0.0
spec:
  minReadySeconds: 60
  selector:
    matchLabels:
      app: mongo-server
      release: 1.0.0
  
  template:
    metadata:
      labels:
        app: mongo-server
        release: 1.0.0
    
    spec:
      containers:
      - name: mongo-server
  
        image: "bitnami/mongodb"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-server
  labels:
    app: mongo-server
    release: 1.0.0
spec:
  type: NodePort
  selector:
    app: mongo-server
    release: 1.0.0
  ports:
  - port: 27024
    targetPort: 27017